### ISSUE TITLE
Two provided links appear broken

### ISSUE THREAD

**Issue by Atavic** [securityfirst/tent#11]
I understand they aren't broken, but letting users click on the 2nd link under [oauth section](https://github.com/securityfirst/tent#oauth) gives that impression, leading to a 404 page.

Maybe it's better to make the 2nd link unclickable.

Same with link in [sample repo](https://github.com/securityfirst/tent#sample-repo) it's better to clarify that the link is used for Umbrella and not as a direct link.

**Comment by klaidliadon** [comment]
Fixed in https://github.com/securityfirst/tent/commit/4a976b4ed609a64169b5e027c32817e0023e828b
