### ISSUE TITLE
missing link + error on run

### ISSUE THREAD

**Issue by JOduMonT** [securityfirst/tent#13]
Hi;

1. In the [Binary part](https://github.com/securityfirst/tent#binary) the [Download the latest version of the binary link](https://github.com/securityfirst/tentreleases/latest) is dead.

than I'm not sure it is related but

2. when I run

`go get github.com/securityfirst/tenttent`

I receive this error:

> \# cd .; git clone -- https://github.com/securityfirst/tenttent /home/----/go/src/github.com/securityfirst/tenttent
> Cloning into '/home/----/go/src/github.com/securityfirst/tenttent'...
> fatal: could not read Username for 'https://github.com': terminal prompts disabled
> package github.com/securityfirst/tenttent: exit status 128

**Comment by klaidliadon** [comment]
Fixed in https://github.com/securityfirst/tent/commit/7b767a97aa9ecfc0967e67679a00317303814118

**Comment by rorymbyrne** [comment]
Hi @JOduMonT thanks for pointing that out, we have now fixed it. I hope you are finding Umbrella and Tent useful!
